import { NextRequest, NextResponse } from 'next/server';
import { readMiscTasks, removeMiscTask } from '../misc-store-utils';

export const runtime = 'nodejs';

// Promote moves a misc-notes capture into a General backlog. Misc tasks are by
// construction unreferenced (no Current/Today/journal/roadmap entries), so the
// fresh id generated by /api/tasks/add loses nothing.
export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as { taskId?: unknown; listType?: unknown };
    const taskId = typeof body.taskId === 'string' ? body.taskId.trim() : '';
    const listType = body.listType === 'want-to-do' ? 'want-to-do' : body.listType === 'have-to-do' ? 'have-to-do' : null;
    if (!taskId) {
      return NextResponse.json({ success: false, error: 'taskId is required' }, { status: 400 });
    }
    if (!listType) {
      return NextResponse.json(
        { success: false, error: 'listType must be have-to-do or want-to-do' },
        { status: 400 },
      );
    }

    const task = readMiscTasks().tasks.find((candidate) => candidate.id === taskId);
    if (!task) {
      return NextResponse.json({ success: false, error: 'Task not found in misc notes' }, { status: 404 });
    }

    const response = await fetch('http://localhost:3000/api/tasks/add', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        task: task.text,
        listType,
        notesMarkdown: task.notesMarkdown,
      }),
    });
    const data = await response.json();
    if (!response.ok || !data.success) {
      return NextResponse.json(
        { success: false, error: data.error || 'Failed to promote task' },
        { status: 502 },
      );
    }

    removeMiscTask(taskId);
    return NextResponse.json({ success: true, taskId: data.taskId, task: data.task, listType });
  } catch (error) {
    console.error('Error promoting misc task:', error);
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}
